name: Workflow Keepalive

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1